export const CATEGORY_CREATE_REQUEST = "CATEGORY_CREATE_REQUEST";
export const CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS";
export const CATEGORY_CREATE_FAILED = "CATEGORY_CREATE_FAILED";

export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAILED = "CATEGORY_LIST_FAILED";

export const CATEGORY_DETAIL_REQUEST = "CATEGORY_DETAIL_REQUEST";
export const CATEGORY_DETAIL_SUCCESS = "CATEGORY_DETAIL_SUCCESS";
export const CATEGORY_DETAIL_FAILED = "CATEGORY_DETAIL_FAILED";

export const CATEGORY_UPDATE_REQUEST = "CATEGORY_UPDATE_REQUEST";
export const CATEGORY_UPDATE_SUCCESS = "CATEGORY_UPDATE_SUCCESS";
export const CATEGORY_UPDATE_FAILED = "CATEGORY_UPDATE_FAILED";

export const CATEGORY_DELETE_REQUEST = "CATEGORY_DELETE_REQUEST";
export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_FAILED = "CATEGORY_DELETE_FAILED";
export const CATEGORY_DELETE = "CATEGORY_DELETE"

export const SUB_CATEGORY_REQUEST = "SUB_CATEGORY_REQUEST";
export const SUB_CATEGORY_SUCCESS = "SUB_CATEGORY_SUCCESS";
export const SUB_CATEGORY_FAILED = "SUB_CATEGORY_FAILED";