export const COUPON_LIST_REQUEST = 'COUPON_LIST_REQUEST'
export const COUPON_LIST_SUCCESS = 'COUPON_LIST_SUCCESS'
export const COUPON_LIST_FAILED = 'COUPON_LIST_FAILED'

export const COUPON_REMOVE_USED_REQUEST = 'COUPON_REMOVE_USED_REQUEST'
export const COUPON_REMOVE_USED_SUCCESS = 'COUPON_REMOVE_USED_SUCCESS'
export const COUPON_REMOVE_USED_FAILED = 'COUPON_REMOVE_USED_FAILED'

export const COUPON_CREATE_REQUEST = 'COUPON_CREATE_REQUEST'
export const COUPON_CREATE_SUCCESS = 'COUPON_CREATE_SUCCESS'
export const COUPON_CREATE_FAILED = 'COUPON_CREATE_FAILED'
