export const SIZE_CREATE_REQUEST = "SIZE_CREATE_REQUEST";
export const SIZE_CREATE_SUCCESS = "SIZE_CREATE_SUCCESS";
export const SIZE_CREATE_FAILED = "SIZE_CREATE_FAILED";

export const SIZE_LIST_REQUEST = "SIZE_LIST_REQUEST";
export const SIZE_LIST_SUCCESS = "SIZE_LIST_SUCCESS";
export const SIZE_LIST_FAILED = "SIZE_LIST_FAILED";

export const SIZE_DETAIL_REQUEST = "SIZE_DETAIL_REQUEST";
export const SIZE_DETAIL_SUCCESS = "SIZE_DETAIL_SUCCESS";
export const SIZE_DETAIL_FAILED = "SIZE_DETAIL_FAILED";

export const SIZE_UPDATE_REQUEST = "SIZE_UPDATE_REQUEST";
export const SIZE_UPDATE_SUCCESS = "SIZE_UPDATE_SUCCESS";
export const SIZE_UPDATE_FAILED = "SIZE_UPDATE_FAILED";

export const SIZE_DELETE_REQUEST = "SIZE_DELETE_REQUEST";
export const SIZE_DELETE_SUCCESS = "SIZE_DELETE_SUCCESS";
export const SIZE_DELETE_FAILED = "SIZE_DELETE_FAILED";
