export const SUB_CREATE_REQUEST = "SUB_CREATE_REQUEST";
export const SUB_CREATE_SUCCESS = "SUB_CREATE_SUCCESS";
export const SUB_CREATE_FAILED = "SUB_CREATE_FAILED";

export const SUB_LIST_REQUEST = "SUB_LIST_REQUEST";
export const SUB_LIST_SUCCESS = "SUB_LIST_SUCCESS";
export const SUB_LIST_FAILED = "SUB_LIST_FAILED";

export const SUB_DETAIL_REQUEST = "SUB_DETAIL_REQUEST";
export const SUB_DETAIL_SUCCESS = "SUB_DETAIL_SUCCESS";
export const SUB_DETAIL_FAILED = "SUB_DETAIL_FAILED";

export const SUB_UPDATE_REQUEST = "SUB_UPDATE_REQUEST";
export const SUB_UPDATE_SUCCESS = "SUB_UPDATE_SUCCESS";
export const SUB_UPDATE_FAILED = "SUB_UPDATE_FAILED";

export const SUB_DELETE_REQUEST = "SUB_DELETE_REQUEST";
export const SUB_DELETE_SUCCESS = "SUB_DELETE_SUCCESS";
export const SUB_DELETE_FAILED = "SUB_DELETE_FAILED";
