export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAILED = "ADMIN_LOGIN_FAILED";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT = "LOGOUT";

export const ADMIN_CHANGEPW_REQUEST = "ADMIN_CHANGEPW_REQUEST";
export const ADMIN_CHANGEPW_SUCCESS = "ADMIN_CHANGEPW_SUCCESS";
export const ADMIN_CHANGEPW_FAILED = "ADMIN_CHANGEPW_FAILED";

export const ADMIN_PROFILE_REQUEST = "ADMIN_PROFILE_REQUEST";
export const ADMIN_PROFILE_SUCCESS = "ADMIN_PROFILE_SUCCESS";
export const ADMIN_PROFILE_FAILED = "ADMIN_PROFILE_FAILED";
export const ADMIN_PROFILE_RESET = "ADMIN_PROFILE_RESET";

export const ADMIN_UPDATE_REQUEST = "ADMIN_UPDATE_REQUEST";
export const ADMIN_UPDATE_SUCCESS = "ADMIN_UPDATE_SUCCESS";
export const ADMIN_UPDATE_FAILED = "ADMIN_UPDATE_FAILED";