export const VARIATION_CREATE_REQUEST = 'VARIATION_CREATE_REQUEST'
export const VARIATION_CREATE_SUCCESS = 'VARIATION_CREATE_SUCCESS'
export const VARIATION_CREATE_FAILED = 'VARIATION_CREATE_FAILED'

export const VARIATION_LIST_REQUEST = 'VARIATION_LIST_REQUEST'
export const VARIATION_LIST_SUCCESS = 'VARIATION_LIST_SUCCESS'
export const VARIATION_LIST_FAILED = 'VARIATION_LIST_FAILED'

export const VARIATION_DETAIL_REQUEST = 'VARIATION_DETAIL_REQUEST'
export const VARIATION_DETAIL_SUCCESS = 'VARIATION_DETAIL_SUCCESS'
export const VARIATION_DETAIL_FAILED = 'VARIATION_DETAIL_FAILED'

export const VARIATION_UPDATE_REQUEST = 'VARIATION_UPDATE_REQUEST'
export const VARIATION_UPDATE_SUCCESS = 'VARIATION_UPDATE_SUCCESS'
export const VARIATION_UPDATE_FAILED = 'VARIATION_UPDATE_FAILED'

export const VARIATION_DELETE_REQUEST = 'VARIATION_DELETE_REQUEST'
export const VARIATION_DELETE_SUCCESS = 'VARIATION_DELETE_SUCCESS'
export const VARIATION_DELETE_FAILED = 'VARIATION_DELETE_FAILED'

export const SUB_VARIATION_REQUEST = 'SUB_VARIATION_REQUEST'
export const SUB_VARIATION_SUCCESS = 'SUB_VARIATION_SUCCESS'
export const SUB_VARIATION_FAILED = 'SUB_VARIATION_FAILED'

export const SIZE_CREATE_REQUEST = 'SIZE_CREATE_REQUEST'
export const SIZE_CREATE_SUCCESS = 'SIZE_CREATE_SUCCESS'
export const SIZE_CREATE_FAILED = 'SIZE_CREATE_FAILED'

export const SIZE_LIST_REQUEST = 'SIZE_LIST_REQUEST'
export const SIZE_LIST_SUCCESS = 'SIZE_LIST_SUCCESS'
export const SIZE_LIST_FAILED = 'SIZE_LIST_FAILED'

export const SIZE_DETAIL_REQUEST = 'SIZE_DETAIL_REQUEST'
export const SIZE_DETAIL_SUCCESS = 'SIZE_DETAIL_SUCCESS'
export const SIZE_DETAIL_FAILED = 'SIZE_DETAIL_FAILED'

export const SIZE_UPDATE_REQUEST = 'SIZE_UPDATE_REQUEST'
export const SIZE_UPDATE_SUCCESS = 'SIZE_UPDATE_SUCCESS'
export const SIZE_UPDATE_FAILED = 'SIZE_UPDATE_FAILED'

export const SIZE_DELETE_REQUEST = 'SIZE_DELETE_REQUEST'
export const SIZE_DELETE_SUCCESS = 'SIZE_DELETE_SUCCESS'
export const SIZE_DELETE_FAILED = 'SIZE_DELETE_FAILED'
