export const VARIATION_CREATE_REQUEST = 'VARIATION_CREATE_REQUEST'
export const VARIATION_CREATE_SUCCESS = 'VARIATION_CREATE_SUCCESS'
export const VARIATION_CREATE_FAILED = 'VARIATION_CREATE_FAILED'

export const VARIATION_LIST_REQUEST = 'VARIATION_LIST_REQUEST'
export const VARIATION_LIST_SUCCESS = 'VARIATION_LIST_SUCCESS'
export const VARIATION_LIST_FAILED = 'VARIATION_LIST_FAILED'

export const VARIATION_DETAIL_REQUEST = 'VARIATION_DETAIL_REQUEST'
export const VARIATION_DETAIL_SUCCESS = 'VARIATION_DETAIL_SUCCESS'
export const VARIATION_DETAIL_FAILED = 'VARIATION_DETAIL_FAILED'

export const VARIATION_UPDATE_REQUEST = 'VARIATION_UPDATE_REQUEST'
export const VARIATION_UPDATE_SUCCESS = 'VARIATION_UPDATE_SUCCESS'
export const VARIATION_UPDATE_FAILED = 'VARIATION_UPDATE_FAILED'

export const VARIATION_DELETE_REQUEST = 'VARIATION_DELETE_REQUEST'
export const VARIATION_DELETE_SUCCESS = 'VARIATION_DELETE_SUCCESS'
export const VARIATION_DELETE_FAILED = 'VARIATION_DELETE_FAILED'

export const SUB_VARIATION_REQUEST = 'SUB_VARIATION_REQUEST'
export const SUB_VARIATION_SUCCESS = 'SUB_VARIATION_SUCCESS'
export const SUB_VARIATION_FAILED = 'SUB_VARIATION_FAILED'
