export const ADD_ADDRESS = 'ADD_ADDRESS'
export const REMOVE_ADDRESS = 'REMOVE_ADDRESS'

export const ADDRESS_LIST_REQUEST = 'ADDRESS_LIST_REQUEST'
export const ADDRESS_LIST_SUCCESS = 'ADDRESS_LIST_SUCCESS'
export const ADDRESS_LIST_FAILED = 'ADDRESS_LIST_FAILED'
export const ADDRESS_LIST_RESET = 'ADDRESS_LIST_RESET'
