export const CART_ADD_REQUEST = "CART_ADD_REQUEST";
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const REMOVE_ALL_CART = "REMOVE_ALL_CART";