export const CART_ADD_REQUEST = "CART_ADD_REQUEST";
export const CART_ADD_ITEM = "CART_ADD_ITEM";

export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";

export const REMOVE_ITEM = "REMOVE_ITEM";
export const REMOVE_ALL_CART = "REMOVE_ALL_CART";

export const CART_ADD_DATABASE_REQUEST = "CART_ADD_DATABASE_REQUEST";
export const CART_ADD_DATABASE_SUCCESS = "CART_ADD_DATABASE_SUCCESS";
export const CART_ADD_DATABASE_FAILED = "CART_ADD_DATABASE_FAILED";

export const LIST_CART_REQUEST = "LIST_CART_REQUEST";
export const LIST_CART_SUCCESS = "LIST_CART_SUCCESS";
export const LIST_CART_FAILED = "LIST_CART_FAILED";
export const LIST_CART_RESET = "LIST_CART_RESET";

export const REMOVE_CART_ITEM_DATABASE = "REMOVE_CART_ITEM_DATABASE";