export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAILED = 'ORDER_LIST_FAILED'
export const ORDER_LIST_RESET = 'ORDER_LIST_RESET'

export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAILED = 'ORDER_CREATE_FAILED'

export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST'
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS'
export const ORDER_DETAIL_FAILED = 'ORDER_DETAIL_FAILED'
export const ORDER_DETAIL_RESET = 'ORDER_DETAIL_RESET'

export const ORDER_PAYPAL_REQUEST = 'ORDER_PAYPAL_REQUEST'
export const ORDER_PAYPAL_SUCCESS = 'ORDER_PAYPAL_SUCCESS'
export const ORDER_PAYPAL_FAILED = 'ORDER_PAYPAL_FAILED'
