export const PRODUCT_LIST_NEW_REQUEST = "PRODUCT_LIST_NEW_REQUEST";
export const PRODUCT_LIST_NEW_SUCCESS = "PRODUCT_LIST_NEW_SUCCESS";
export const PRODUCT_LIST_NEW_FAILED = "PRODUCT_LIST_NEW_FAILED";