export const PRODUCT_LIST_NEW_REQUEST = "PRODUCT_LIST_NEW_REQUEST";
export const PRODUCT_LIST_NEW_SUCCESS = "PRODUCT_LIST_NEW_SUCCESS";
export const PRODUCT_LIST_NEW_FAILED = "PRODUCT_LIST_NEW_FAILED";

export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAILED = "PRODUCT_LIST_NEW_FAILED";

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAIL_FAILED = "PRODUCT_DETAIL_FAILED";