export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED"
export const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";

export const USER_SENDMAIL_REQUEST = "USER_SENDMAIL_REQUEST";
export const USER_SENDMAIL_SUCCESS = "USER_SENDMAIL_SUCCESS";
export const USER_SENDMAIL_FAILED = "USER_SENDMAIL_FAILED";

export const USER_NEWPW_REQUEST = "USER_NEWPW_REQUEST";
export const USER_NEWPW_SUCCESS = "USER_NEWPW_SUCCESS";
export const USER_NEWPW_FAILED = "USER_NEWPW_FAILED";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILED = "USER_PROFILE_FAILED";
export const USER_PROFILE_RESET = "USER_PROFILE_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAILED = "USER_UPDATE_PROFILE_FAILED";

export const USER_UPDATE_PW_REQUEST = "USER_UPDATE_PW_REQUEST";
export const USER_UPDATE_PW_SUCCESS = "USER_UPDATE_PW_SUCCESS";
export const USER_UPDATE_PW_FAILED = "USER_UPDATE_PW_FAILED";

