export const ADD_WISHLIST_REQUEST = 'ADD_WISHLIST_REQUEST'
export const ADD_WISHLIST_SUCCESS = 'ADD_WISHLIST_SUCCESS'
export const ADD_WISHLIST_FAILED = 'ADD_WISHLIST_FAILED'
export const ADD_WISHLIST = 'ADD_WISHLIST'

export const REMOVE_WISHLIST_REQUEST = 'REMOVE_WISHLIST_REQUEST'
export const REMOVE_WISHLIST_SUCCESS = 'REMOVE_WISHLIST_SUCCESS'
export const REMOVE_WISHLIST_FAILED = 'REMOVE_WISHLIST_FAILED'
export const REMOVE_WISHLIST = 'REMOVE_WISHLIST'

export const LIST_WISHLIST_REQUEST = 'LIST_WISHLIST_REQUEST'
export const LIST_WISHLIST_SUCCESS = 'LIST_WISHLIST_SUCCESS'
export const LIST_WISHLIST_FAILED = 'LIST_WISHLIST_FAILED'
export const LIST_WISHLIST_RESET = 'LIST_WISHLIST_RESET'
